### ISSUE TITLE
Strange results with size_pbf column of geofabric_zones

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#10]
``` r
library(geofabric)
sort(table(geofabric_zones$size_pbf, useNA = "ifany"), decreasing = TRUE)[1:5]
#> 
#> [.osm.bz2]    (60 MB)    (77 MB)    (84 MB)   (104 MB) 
#>         56          4          4          4          3
```

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The strange thing is that all the "problematic" countries are in Africa and, if I rerun the code in `data-raw/geofabric_zones.R` I get a different result. 

``` r
sort(table(t_all$size_pbf, useNA = "ifany"), decreasing = TRUE)[1:5]
#> 
#>  (84 MB)  (213 MB) (46.2 MB)   (69 MB)   (99 MB)
#>        5         4         4         4         4 
```

**Comment by Robinlovelace** [comment]
Interesting. We should clearly return a consistent result, a numeric representing MB. This can be done here: 

https://github.com/ITSLeeds/geofabric/blob/54b35d730eeb5593a9c314be3079b9c441bb199c/data-raw/geofabric_zones.R#L97-L99

**Comment by agila5** [comment]
Fixed with the new approach and documented in `data_raw/geofabrik_zones.R`
