### ISSUE TITLE
Add the possibility to download Country data using Standard alpha-3 codes

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#22]
Something like: `get_geofabric("ITA")` or `get_geofabric("GBR")`. 

The codes are reported [here](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements).

**Comment by Robinlovelace** [comment]
Good idea but not sure how important it is: if people know the code, surely they will know the country name?

**Comment by agila5** [comment]
Fixed with the new approach
