### ISSUE TITLE
Bug in get_geofabric with non exact matches

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#27]
For example, if I run `get_geofabric("ABCD")` in interactive mode (which was just a stupid test to check some other changes) then I don't get any warning or message, just an "unrelated" warning that R is going to download a very large file (7.2 GB). 

I didn't understand so I checked and I found that "ABCD" was matched with "Asia" and so everything makes sense now but I think we should add some message if there is no exact match between the input name and the names stored in the `geofabric_zones.rda`. Something like: 

* If there is an exact match: no message or warning;
* If there is a match below the `max_dist` threshold: message
* If there is no match: warning 

Do you agree? Nevertheless it's easy to solve these problem just by changing the `max_dist` parameter (for example `get_geofabric("ABCD", max_dist = "1")` returns the usual warning) so I'm not sure if it does make sense to change the function.

**Comment by Robinlovelace** [comment]
I  agree, maybe just reducing the `max_dist` parameter, or using a more clever fuzzy matching algorithm like `stringdist::amatch()` will solve the issue:  https://rdrr.io/cran/stringdist/man/amatch.html

**Comment by Robinlovelace** [comment]
In the first instance, I'd suggest fixing this by setting `max_dist = 1` as the default. Note: a few lines in the documentation may need to change if you do this. Still I think the +s of making the changes are greater than the -s so thanks for spotting this and opening the issue.

**Comment by agila5** [comment]
Fixed with the new approach but it should be documented
