### ISSUE TITLE
Weird result with query parameter

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#39]
I was working on the OGR_INTERLEAVED_READING problem (and I will submit a draft PR shortly) and I think I found something weird with the query parameter. I'm not sure if it's a bug or not and I can't easily reproduce that with geofabrik only but the following reprex should show the problem. 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

my_url <- "https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf"
sf::st_read(my_url, layer = "points")
#> Reading layer `points' from data source `https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf' using driver `OSM'
#> Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, :
#> GDAL Error 1: Too many features have accumulated in lines layer. Use
#> OGR_INTERLEAVED_READING=YES mode
#> Simple feature collection with 75666 features and 10 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -2.326617 ymin: 53.3142 xmax: -1.039338 ymax: 54.03102
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
sf::st_read(my_url, layer = "points", query = "select * from points")
#> Reading layer `points' from data source `https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf' using driver `OSM'
#> Simple feature collection with 75666 features and 10 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -2.326617 ymin: 53.3142 xmax: -1.039338 ymax: 54.03102
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
```

<sup>Created on 2020-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What's the difference between the two approaches? Why I don't see any warning if I add a query that shouldn't modify anything?

**Comment by Robinlovelace** [comment]
Interesting. Perhaps the way that `sf` dispatches the call to GDAL when there is a query argument hides the warning? This seems like a potential `sf` issue. Thoughts @edzer (and sorry these OSM explorations are generating pesky questions!)?

**Comment by edzer** [comment]
`sf` does nothing unusual, in this case.

**Comment by Robinlovelace** [comment]
Thanks Edzer, but doesn't it seem strange that the warning message from GDAL is not there when the same data is read-in?

**Comment by agila5** [comment]
Hi everyone! I think I should explain a little bit better my first message. I think that that result (created using `sf::st_read(my_url, layer = "points", query = "select * from points")`) is weird because it returns exactly the same output as the same command without the query parameter without the warning message. 

IMO this is a problem because the output of `sf::st_read(my_url, layer = "points", query = "select * from points")` exhibits the same problem as the first output (since they both have the same number of rows).

I know that this is a pathological example but I was also wondering if the same situation may occur for other types of data. The problem is that I'm not sure how to test that (i.e. if a warning message gets suppressed using the query parameter). 

I hope it make sense now. I know that this is really unimportant (since we are also going to ignore the direct import of .osm.pbf file) so maybe we can just ignore this stuff.

**Comment by Robinlovelace** [comment]
Related question, how will the new gpkg approach deal with `query` parameters? Not even sure if it's possible to add queries when converting from pbf to gpkg but maybe worth checking to see if it makes the process faster.

**Comment by agila5** [comment]
> Related question, how will the new gpkg approach deal with query parameters? Not even sure if it's possible to add queries when converting from pbf to gpkg but maybe worth checking to see if it makes the process faster.

Actually yes, using *select* and *where* arguments from [ogr2ogr](https://gdal.org/programs/ogr2ogr.html). I'm not sure how to merge those parameters with current `key`, `value` and `selected_columns` parameters but I will check that tomorrow (and add an example in the PR).

**Comment by agila5** [comment]
Not relevant anymore
