### ISSUE TITLE
Create local version of osmconf.ini

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#41]
When we create the new version of the CONFIG_FILE for OSM GDAL Open Options we use the following code

https://github.com/ITSLeeds/geofabrik/blob/73dd18af8f47284167a32f9190e673603c589a6e/R/read_pbf.R#L135

which clearly doesn't work if there is no internet connection. Does it make sense to create "local" version of gdal/osmconf.ini file and that local version to the package? In this way, as long as the user has already downloaded the .osm.pbf file and saved it in the GF_DOWNLOAD_DIRECTORY, the get_geofabrik function could also be used offline.

**Comment by Robinlovelace** [comment]
> Does it make sense to create "local" version of gdal/osmconf.ini file and that local version to the package?

Most definitely a good idea, and makes it less vulnerable to upstream changes in GDAL. I think it should live in `inst` or even an `inst/osmconf/` folder where multiple settings could live in future versions of this package.

**Comment by agila5** [comment]
Fixed with the new approach
