### ISSUE TITLE
oe_update()

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextractr#64]
I think a small function to download more recent versions of a file could be really useful. Building on https://github.com/ITSLeeds/osmextractr/issues/33 I think it could simply be:

``` r
library(osmextractr)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/
oe_update = function(place, ...) {
  oe_get(place = place, ..., force_download = TRUE, download_only = TRUE)
}
oe_update("Isle of Wight")
#> [1] "/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/data/osm/geofabrik_isle-of-wight-latest.gpkg"
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by agila5** [comment]
Agree but I would also add `force_vectortranslate` otherwise the .gpkg file is not update

**Comment by agila5** [comment]
I will try to add a PR after dinner!

**Comment by Robinlovelace** [comment]
Just a thought on this: could it print the date the old file was last modified? Not sure if R has a way to do that...

**Comment by agila5** [comment]
Something like this? 

``` r
file.info("../osmext_data/geofabrik_andorra-latest.osm.pbf")[c("mtime", "ctime", "atime")]
#>                                                 mtime ctime atime
#> ../osmext_data/geofabrik_andorra-latest.osm.pbf  <NA>  <NA>  <NA>
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Anyway yesterday I was thinking about this problem and, IMO, the most useful approach for a new `oe_update()` function would be to update all the `.osm.pbf` and `.gpkg` file stored in the `download_directory`. So the input is the path of the directory and the output is the path of all updated and transalted files (maybe with `invisible()`). What do you think?

**Comment by Robinlovelace** [comment]
> What do you think?

That sounds like a sensible to me, it's really useful for the user to see the file path of the updated files. A message showing the details including before/after file size and date of modification would be a bonus!

**Comment by Robinlovelace** [comment]
Showing the before/after file size could provide an indication of the extent of the changes.
