### ISSUE TITLE
Function/arguments to get OSM data with default additional attributes

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextractr#65]
In previous versions the data was downloaded with the following extra attributes:

```
c("maxspeed", "oneway", "lanes")
```

It would be useful to have a way to do that, e.g. with `oe_get_with_speed()` or similar wrappers around `oe_get()`.

**Comment by agila5** [comment]
At the moment it's possible to get extra attributes with the parameter `extra_attributes`. I'm not so sure that we should add ad-hoc function for these cases since there are way too many possibilities
