### ISSUE TITLE
pkgdown deployment is failing

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/osmextractr#74]
Also affects other packages: https://github.com/saferactive/saferactive/issues/26

**Comment by agila5** [comment]
Oh ok, that was the question that I wanted to ask, thanks!

**Comment by Robinlovelace** [comment]
Hmm still failing, for a different reason this time: https://github.com/ITSLeeds/osmextractr/runs/869825219#step:8:28

Let's give it a few days...
