### ISSUE TITLE
Uniform verbose parameters

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#75]
On a second thought I think that the idea of creating three different parameters (i.e. `oe_verbose`, `oe_quiet` and `quiet`) for showing a more detailed description of what's happening in the function is unnecessarily complicated. I would simply use `quiet` for all of them and, at the end, set `quiet = quiet` in `sf::st_read`. In this way you get all the extra messages or none of them.

**Comment by Robinlovelace** [comment]
All or nothing sounds reasonable. Simplicity is good!
