### ISSUE TITLE
Use functions without loading the package

### ISSUE THREAD

**Issue by agila5** [ITSLeeds/osmextractr#81]
I have no idea if this is possible or not (or maybe it's just a problem of the current approach), but I was wondering if we could make the functions work without loading the package: 

``` r
osmextractr::oe_get("Andorra")
#> Error in load_provider_data(provider): object 'geofabrik_zones' not found
```

<sup>Created on 2020-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem is clear (i.e. the provider's databases are not loaded). Is it possible/easy to fix that?  Not a priority.

**Comment by Robinlovelace** [comment]
Fully agree with that. Easy fix that I can help with having seen a similar issue in stats19.

**Comment by Robinlovelace** [comment]
After that it works:

``` r
osmextractr::oe_get("Andorra")
#> Reading layer `lines' from data source `/tmp/RtmpCXAv7v/geofabrik_andorra-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 5992 features and 9 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 0.975577 ymin: 42.32422 xmax: 1.824654 ymax: 42.78834
#> geographic CRS: WGS 84
```

<sup>Created on 2020-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by agila5** [comment]
Awesome,  thanks
